"""
App entrypoint. Run with: uvicorn app.main:app --reload
Then visit http://localhost:8000/docs for interactive API docs (auto-generated by FastAPI).
"""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.routers import documents, chat

app = FastAPI(title="Document RAG Chatbot API", version="1.0.0")

# Allows your frontend (running on a different port) to call this API from the browser.
# In real production you'd restrict allow_origins to your actual frontend domain.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(documents.router)
app.include_router(chat.router)


@app.get("/")
def root():
    return {"status": "ok", "message": "RAG backend is running. See /docs for API reference."}
